export const FLOATING_PINS = [
  { name: "San Francisco", left: "4%", top: "12%", anim: "A", delay: "0s", dur: "11s" },
  { name: "Los Angeles", left: "86%", top: "60%", anim: "B", delay: "1.4s", dur: "13s" },
  { name: "San Diego", left: "69%", top: "7%", anim: "C", delay: "2.2s", dur: "10s" },
  { name: "Sacramento", left: "12%", top: "71%", anim: "A", delay: "0.6s", dur: "14s" },
  { name: "San Jose", left: "51%", top: "83%", anim: "B", delay: "3.8s", dur: "12s" },
  { name: "Oakland", left: "90%", top: "27%", anim: "C", delay: "1.8s", dur: "11s" },
  { name: "Fresno", left: "37%", top: "3%", anim: "A", delay: "5.0s", dur: "10s" },
  { name: "Long Beach", left: "1%", top: "43%", anim: "B", delay: "2.8s", dur: "13s" },
  { name: "Irvine", left: "76%", top: "47%", anim: "C", delay: "4.4s", dur: "9s" },
  { name: "Bakersfield", left: "24%", top: "87%", anim: "A", delay: "6.2s", dur: "12s" },
  { name: "Riverside", left: "57%", top: "36%", anim: "B", delay: "7.0s", dur: "11s" },
  { name: "Santa Ana", left: "42%", top: "54%", anim: "C", delay: "3.2s", dur: "10s" },
  { name: "Anaheim", left: "18%", top: "30%", anim: "B", delay: "8.0s", dur: "13s" },
  { name: "Chula Vista", left: "80%", top: "80%", anim: "A", delay: "5.6s", dur: "11s" },
  { name: "Stockton", left: "31%", top: "20%", anim: "C", delay: "0.4s", dur: "10s" },
  { name: "Fremont", left: "63%", top: "67%", anim: "A", delay: "4.0s", dur: "12s" },
  { name: "Modesto", left: "8%", top: "57%", anim: "B", delay: "6.8s", dur: "11s" },
  { name: "Oxnard", left: "93%", top: "46%", anim: "C", delay: "2.0s", dur: "10s" },
  { name: "Huntington Beach", left: "47%", top: "15%", anim: "A", delay: "7.4s", dur: "13s" },
  { name: "Santa Rosa", left: "71%", top: "91%", anim: "B", delay: "1.0s", dur: "9s" },
  { name: "Sunnyvale", left: "22%", top: "48%", anim: "C", delay: "5.4s", dur: "11s" },
  { name: "Pasadena", left: "55%", top: "24%", anim: "A", delay: "3.0s", dur: "12s" },
  { name: "Berkeley", left: "84%", top: "13%", anim: "B", delay: "8.6s", dur: "10s" },
  { name: "Salinas", left: "35%", top: "75%", anim: "C", delay: "6.4s", dur: "13s" },
];
